<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterHsrSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('character_hsrs')->insert([
            [
                'name' => "Acheron",
                'path' => "Nihility",
                'element' => "Lightning",
                'role' => "DPS",
                'detail' => "Seorang pengembara yang mengaku sebagai Penjaga Galaksi. Nama aslinya tidak diketahui, dan dia berjalan di kosmos sendirian, membawa pedang panjang.
                Meskipun menyendiri dan pendiam, pedangnya menyambar seperti petir yang menyambar. Namun, dia selalu menyerang dengan sarung pedangnya, tidak pernah menghunus pedangnya dengan bebas.\r\n
                Preferensi Stats: SPD(Cukup jika Acheron telah sampai di SPD 134+ | Jika satu tim dengan sparkle, Abaikan Stats SPD) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Ultimate > Skill = Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "S",
                'lightcone_sign_id' => 1,
                'lightcone_alt1_id' => 39,
                'lightcone_alt2_id' => 33,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 1,
                'planar_opt1_id' => 7,
                'planar_opt2_id' => 12,
                'image' => "Acheron.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Argenti",
                'path' => "Erudition",
                'element' => "Physical",
                'role' => "DPS",
                'detail' => "Seorang ksatria klasik dari Knights of Beauty. Lugas dan terus terang, pria yang mulia dan mengagumkan ini mengembara di jagat raya sendirian, dengan teguh mengikuti Path of Beauty.
                Menjunjung tinggi nama baik Kecantikan adalah tugas Argenti. Untuk memenuhi tanggung jawab ini, seseorang harus saleh saat memulai pertempuran, dan harus membuat lawannya menyerah dengan sukarela saat menyerang dengan tombaknya.\r\n
                Preferensi Stats: SPD(Breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Ultimate > Skill = Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "B",
                'tier_pf' => "S",
                'lightcone_sign_id' => 5,
                'lightcone_alt1_id' => 53,
                'lightcone_alt2_id' => 87,
                'relic_opt1_id' => 2,
                'relic_opt2_id' => 11,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 6,
                'image' => "Argenti.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Arlan",
                'path' => "Destruction",
                'element' => "Lightning",
                'role' => "DPS",
                'detail' => "Dia adalah kepala departemen keamanan Herta Space Station yang sering terlihat bersama seekor anjing bernama Peppy.\r\n
                Preferensi Stats: SPD (Breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Ultimate = Talent > Basic",
                'rarity' => "4star",
                'tier_moc' => "D",
                'tier_pf' => "D",
                'lightcone_sign_id' => 55,
                'lightcone_alt1_id' => 84,
                'lightcone_alt2_id' => 89,
                'relic_opt1_id' => 1,
                'relic_opt2_id' => 9,
                'planar_opt1_id' => 10,
                'planar_opt2_id' => 4,
                'image' => "Arlan.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Asta",
                'path' => "Harmony",
                'element' => "Fire",
                'role' => "Support",
                'detail' => "Dia adalah astronom utama yang penuh rasa ingin tahu dan bertanggung jawab untuk menangani urusan Stasiun Luar Angkasa Herta, termasuk mengelola staf dan merespons Persekutuan Inteligensia.\r\n
                Preferensi Stats: EHR(67%) > SPD (Breakpoint) > ATK% > HP% = DEF% = Break Effect%
                Prioritas Skill: Skill = Talent > Ultimate > Basic",
                'rarity' => "4star",
                'tier_moc' => "B",
                'tier_pf' => "A",
                'lightcone_sign_id' => 33,
                'lightcone_alt1_id' => 27,
                'lightcone_alt2_id' => 37,
                'relic_opt1_id' => 14,
                'relic_opt2_id' => 11,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 8,
                'image' => "Asta.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Aventurine",
                'path' => "Preservation",
                'element' => "Imaginary",
                'role' => "Sustain",
                'detail' => "Seorang manajer senior di Departemen Investasi Strategis IPC dan salah satu dari Sepuluh Hati Batu. Batu Pijarnya adalah Aventurine yang penuh dengan siasat. Dia memiliki jiwa yang suka bersenang-senang dan tidak segan-segan mengambil risiko. Senyumnya yang konstan membuat orang sulit untuk mengetahui perasaannya yang sebenarnya.
                Dia memenangkan posisinya saat ini dengan bertaruh melawan takdir itu sendiri. Dia memandang hidup sebagai investasi dengan risiko tinggi dan hasil yang tinggi, dan dia memainkan pertaruhan ini dengan sangat mudah.\r\n
                Preferensi Stats: DEF% (Target 4000) >= SPD > CRIT DMG > CRIT RATE > Effect RES
                Prioritas Skill: Skill > Talent > Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "S+",
                'lightcone_sign_id' => 41,
                'lightcone_alt1_id' => 49,
                'lightcone_alt2_id' => 15,
                'relic_opt1_id' => 8,
                'relic_opt2_id' => 15,
                'planar_opt1_id' => 6,
                'planar_opt2_id' => 2,
                'image' => "Aventurine.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Bailu",
                'path' => "Abundance",
                'element' => "Lightning",
                'role' => "Sustain",
                'detail' => "Tetua Tinggi Vidyadhara yang lincah, juga dikenal sebagai Wanita Penyembuh di Xianzhou Luofu yang selalu berusaha melarikan diri dari Komisi Alkimia. Meskipun keahlian dan pengetahuannya dalam bidang pengobatan tidak mengenal batas, dia sering meresepkan pengobatan yang tidak konvensional.\r\n
                Preferensi Stats: SPD (breakpoint) > HP% > Effect RES% = DEF%
                Prioritas Skill: Talent > Ultimate > Skill > Basic",
                'rarity' => "5star",
                'tier_moc' => "B",
                'tier_pf' => "B",
                'lightcone_sign_id' => 52,
                'lightcone_alt1_id' => 86,
                'lightcone_alt2_id' => 64,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 12,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Bailu.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Black Swan",
                'path' => "Nihility",
                'element' => "Wind",
                'role' => "Sub-DPS",
                'detail' => "Seorang Peramal dari Garden of Recollection. Peramal yang misterius dan elegan.
                Bears a warm smile and is willing to patiently heed the words of another, and thus uses such means as a pretext to enter 'memories' and gain a comprehension over the flow of all information. Feels strongly about collecting unique memories, yet the thoughts that guide her are hard to glean.\r\n
                Preferensi Stats: EHR (100-120%) > SPD (Breakpoint) > ATK% > Break Effect
                Prioritas Skill: Talent > Ultimate = Skill = Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "S+",
                'lightcone_sign_id' => 66,
                'lightcone_alt1_id' => 60,
                'lightcone_alt2_id' => 27,
                'relic_opt1_id' => 14,
                'relic_opt2_id' => 13,
                'planar_opt1_id' => 8,
                'planar_opt2_id' => 4,
                'image' => "Black Swan.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Blade",
                'path' => "Destruction",
                'element' => "Wind",
                'role' => "DPS",
                'detail' => "Seorang anggota Pemburu Stellaron dan pendekar pedang yang meninggalkan tubuhnya untuk menjadi pedang. Dia bersumpah setia kepada Destiny's Slave dan memiliki kemampuan penyembuhan diri yang menakutkan.\r\n
                Preferensi Stats: SPD (breakpoint) > CRIT RATE = CRIT DMG > HP%
                Prioritas Skill: Basic > Talent = Skill >= Ultimate",
                'rarity' => "5star",
                'tier_moc' => "A",
                'tier_pf' => "A",
                'lightcone_sign_id' => 84,
                'lightcone_alt1_id' => 2,
                'lightcone_alt2_id' => 31,
                'relic_opt1_id' => 9,
                'relic_opt2_id' => 14,
                'planar_opt1_id' => 10,
                'planar_opt2_id' => 6,
                'image' => "Blade.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Bronya",
                'path' => "Harmony",
                'element' => "Wind",
                'role' => "Support",
                'detail' => "Dia adalah komandan Pengawal Silvermane dan Penjaga Agung Belobog saat ini (kesembilan belas). Berasal dari Dunia Bawah dan dari panti asuhan yang sama dengan Seele, dia dipilih dari beberapa anak untuk menjadi Penjaga Agung berikutnya, dan kemudian diadopsi oleh Cocolia.\r\n
                Preferensi Stats: SPD (Breakpoint) > CRIT DMG% > HP = DEF > Effect RES% (30% Jika menggunakan Broken Keel)
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "S",
                'lightcone_sign_id' => 11,
                'lightcone_alt1_id' => 59,
                'lightcone_alt2_id' => 63,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 9,
                'planar_opt1_id' => 2,
                'planar_opt2_id' => 5,
                'image' => "Bronya.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Clara",
                'path' => "Destruction",
                'element' => "Physical",
                'role' => "DPS",
                'detail' => "Dia adalah seorang gadis muda pemalu yang menjadi yatim piatu di usia dini, ditemani oleh sebuah mekanisme kuno bernama Svarog. Keinginan terbesarnya adalah memiliki sebuah keluarga.
                \r\nPreferensi Stats: SPD (Optional) = CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Talent > Skill = Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "A",
                'tier_pf' => "A",
                'lightcone_sign_id' => 10,
                'lightcone_alt1_id' => 55,
                'lightcone_alt2_id' => 89,
                'relic_opt1_id' => 2,
                'relic_opt2_id' => 9,
                'planar_opt1_id' => 6,
                'planar_opt2_id' => 10,
                'image' => "Clara.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Dan Heng",
                'path' => "The Hunt",
                'element' => "Wind",
                'role' => "DPS",
                'detail' => "Penjaga kereta yang dingin dan pendiam serta pengarsip Astral Express. Dengan menggunakan tombak bernama Cloud-Piercer, dia bergabung dengan kru Express untuk melarikan diri dari masa lalunya yang terpencil.
                \r\nPreferensi Stats: SPD (breakpoint) = CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill = Ultimate > Talent > Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "D",
                'lightcone_sign_id' => 38,
                'lightcone_alt1_id' => 78,
                'lightcone_alt2_id' => 56,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 11,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 10,
                'image' => "Dan Heng.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Dan Heng • Imbibitor Lunae",
                'path' => "Destruction",
                'element' => "Imaginary",
                'role' => "DPS",
                'detail' => "Wujud Vidyadhara Dan Heng yang sebenarnya, terungkap setelah menerima sisa kekuatan dari reinkarnasi sebelumnya dari Imbibitor Lunae. Setelah menerima tanduk agung di atas mahkotanya, dia harus menerima semua kelebihan dan kekurangan yang dikaitkan dengan orang tersebut.
                \r\nPreferensi Stats: SPD (breakpoint) = CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Basic > Skill = Talent = Ultimate",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "B",
                'lightcone_sign_id' => 10,
                'lightcone_alt1_id' => 55,
                'lightcone_alt2_id' => 89,
                'relic_opt1_id' => 17,
                'relic_opt2_id' => 11,
                'planar_opt1_id' => 10,
                'planar_opt2_id' => 4,
                'image' => "Dan Heng Imbibitor Lunae.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Dr. Ratio",
                'path' => "The Hunt",
                'element' => "Imaginary",
                'role' => "DPS",
                'detail' => "Seorang anggota Intelligentsia Guild yang jujur dan egois, yang sering menyembunyikan penampilannya dengan patung gips yang aneh.
                Dia menunjukkan kecerdasan dan bakat yang tak tertandingi sejak masa mudanya, tetapi sekarang menyebut dirinya sebagai seorang Mundan. Dia sangat percaya bahwa kecerdasan dan kreativitas tidak terbatas pada orang jenius. Dia berusaha untuk mendistribusikan pengetahuan ke seluruh alam semesta untuk menyembuhkan penyakit yang terus-menerus bernama ketidaktahuan.
                \r\nPreferensi Stats: SPD (breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Talent > Skill > Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "C",
                'lightcone_sign_id' => 7,
                'lightcone_alt1_id' => 96,
                'lightcone_alt2_id' => 56,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 15,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 6,
                'image' => "Dr. Ratio.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Fu Xuan",
                'path' => "Preservation",
                'element' => "Quantum",
                'role' => "Sustain",
                'detail' => "Peramal Utama yang percaya diri namun blak-blakan dari Komisi Ramalan Xianzhou Luofu dan salah satu dari Enam Kusir. Dia menghitung rute Xianzhou Luofu dan meramalkan hasil dari kejadian di masa depan, karena dia merasa bahwa apa yang dia lakukan adalah tindakan yang paling bijaksana.
                \r\nPreferensi Stats: SPD (breakpoint) = HP% >= DEF% > Effect RES%
                Prioritas Skill: Talent > Skill > Ultimate = Basic",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "S+",
                'lightcone_sign_id' => 73,
                'lightcone_alt1_id' => 49,
                'lightcone_alt2_id' => 43,
                'relic_opt1_id' => 9,
                'relic_opt2_id' => 6,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Fu Xuan.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Gallagher",
                'path' => "Abundance",
                'element' => "Fire",
                'role' => "Sustain",
                'detail' => "Seorang petugas keamanan dari Bloodhound Family di Penacony. Dia juga seorang mixologist yang jorok dan malas. Meskipun pakaiannya tidak terorganisir dan santai dalam cara dia membuat minuman, dia selalu sopan terhadap tamu tetapi tetap waspada terhadap dirinya sendiri.
                Dia tampaknya merupakan karakter dengan masa lalu yang rumit, namun tidak pernah secara aktif menyebutkan detail apa pun.
                Belakangan terungkap bahwa ia memiliki hubungan erat dengan Kematian yang telah tiba di Penacony, dan merupakan pelayan Enigmata.
                \r\nPreferensi Stats: SPD (Semaksimal Mungkin) > Break Effect % (Hingga 150%) > Effect RES% > HP% = DEF%
                Prioritas Skill: Talent > Skill > Basic > Ultimate",
                'rarity' => "4star",
                'tier_moc' => "A",
                'tier_pf' => "A",
                'lightcone_sign_id' => 52,
                'lightcone_alt1_id' => 26,
                'lightcone_alt2_id' => 61,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 12,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Gallagher.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Gepard",
                'path' => "Preservation",
                'element' => "Ice",
                'role' => "Sustain",
                'detail' => "Dia adalah kapten Pengawal Silvermane dan berasal dari keluarga bangsawan Landau di Belobog, yang bertanggung jawab atas pertahanan kota dan menjaga perdamaian.
                \r\nPreferensi Stats: SPD (Breakpoint) = DEF% > HP% = Effect RES%
                Prioritas Skill: Ultimate > Skill = Talent = Basic",
                'rarity' => "5star",
                'tier_moc' => "B",
                'tier_pf' => "B",
                'lightcone_sign_id' => 49,
                'lightcone_alt1_id' => 43,
                'lightcone_alt2_id' => 21,
                'relic_opt1_id' => 8,
                'relic_opt2_id' => 10,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Gepard.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Guinaifen",
                'path' => "Nihility",
                'element' => "Fire",
                'role' => "Sub-DPS",
                'detail' => "Seorang pengelana yang akhirnya tinggal di Xianzhou secara tidak sengaja. Dia sekarang menjadi penampil jalanan yang bersemangat dan lincah, dan telah menguasai banyak akrobat Xianzhou seperti bernapas dengan api, menelan pedang, menyeimbangkan mangkuk, menari dengan payung, menarik leher, dan menghancurkan batu besar, dan masih banyak lagi.
                \r\nPreferensi Stats: EHR(67%) > SPD (Breakpoint) > ATK% > HP% = DEF% = Break Effect%
                Prioritas Skill: Skill = Talent > Ultimate > Basic",
                'rarity' => "4star",
                'tier_moc' => "B",
                'tier_pf' => "A",
                'lightcone_sign_id' => 33,
                'lightcone_alt1_id' => 27,
                'lightcone_alt2_id' => 37,
                'relic_opt1_id' => 14,
                'relic_opt2_id' => 4,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 8,
                'image' => "Guinaifen.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Hanya",
                'path' => "Harmony",
                'element' => "Physical",
                'role' => "Support",
                'detail' => "Salah satu hakim di Komisi Sepuluh Penguasa. Dari empat tugas hakim - penahanan, pemenjaraan, hukuman, dan interogasi - Hanya dibebankan dengan tugas terakhir. Dia mengkhususkan diri dalam membaca karma dan dosa para penjahat, dan mencatat kejahatan dan hukuman mereka dengan Kuas Oracle.
                Karena dia menghabiskan hari-harinya menggunakan mimpi untuk memprediksi pelanggaran karma dan harus menanggung banjir informasi yang deras mengenai tindakan para mara, dia telah lama menjadi tumpul terhadap semua hal di dunia. Hanya ketika dia bekerja dengan saudara perempuannya dan sesama hakim, Xueyi, Hanya sejenak akan mengungkapkan sifat aslinya.
                \r\nPreferensi Stats: SPD > HP = DEF > Break Effect = Effect RES% (30% Jika menggunakan Broken Keel)
                Prioritas Skill: Ultimate >= Talent > Skill = Basic",
                'rarity' => "4star",
                'tier_moc' => "B",
                'tier_pf' => "B",
                'lightcone_sign_id' => 47,
                'lightcone_alt1_id' => 48,
                'lightcone_alt2_id' => 63,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 16,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Hanya.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Herta",
                'path' => "Erudition",
                'element' => "Ice",
                'role' => "DPS",
                'detail' => "Anggota #83 dari Genius Society, dia adalah penguasa Stasiun Luar Angkasa Herta, di mana dia muncul dalam bentuk boneka yang dia tiru dari dirinya yang lebih muda. Dia berkolaborasi dengan Screwllum, Ruan Mei, dan Stephen Lloyd untuk menciptakan Simulated Universe, untuk meneliti sifat misterius Aeons. Dia juga seorang Emanator dari Nous the Erudition.
                \r\nPreferensi Stats: SPD (breakpoint) = CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill = Talent > Ultimate > Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "S+",
                'lightcone_sign_id' => 53,
                'lightcone_alt1_id' => 32,
                'lightcone_alt2_id' => 8,
                'relic_opt1_id' => 7,
                'relic_opt2_id' => 11,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 6,
                'image' => "Herta.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Himeko",
                'path' => "Erudition",
                'element' => "Fire",
                'role' => "DPS",
                'detail' => "Seorang ilmuwan petualang yang menemukan dan memperbaiki kereta api yang terdampar saat masih kecil, dia sekarang menjelajahi alam semesta dengan Astral Express sebagai navigatornya.
                \r\nPreferensi Stats: SPD (breakpoint) = CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "C",
                'tier_pf' => "S",
                'lightcone_sign_id' => 53,
                'lightcone_alt1_id' => 32,
                'lightcone_alt2_id' => 8,
                'relic_opt1_id' => 15,
                'relic_opt2_id' => 13,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 6,
                'image' => "Himeko.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Hook",
                'path' => "Destruction",
                'element' => "Fire",
                'role' => "DPS",
                'detail' => "Bos yang memproklamirkan diri sebagai pasukan petualangan The Moles dan putri angkat Fersman. Dia memandang hidup sebagai kesempatan untuk kebebasan dan petualangan yang tak terhitung jumlahnya.
                \r\nPreferensi Stats: SPD (breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "C",
                'lightcone_sign_id' => 55,
                'lightcone_alt1_id' => 89,
                'lightcone_alt2_id' => 82,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 4,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 10,
                'image' => "Hook.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Huohuo",
                'path' => "Abundance",
                'element' => "Wind",
                'role' => "Sustain",
                'detail' => "Seorang gadis Foxian yang menyedihkan dan tak berdaya yang juga merupakan seorang Hakim Komisi Sepuluh Penguasa yang sedang dalam pelatihan, yang takut akan hantu tetapi harus menangkap mereka. Karena memiliki heliobus bernama Tail yang disegel di ekornya oleh para hakim Komisi Sepuluh Penguasa, dia menjadi orang yang dikutuk yang menarik makhluk yang tidak manusiawi.
                Dia takut pada setan dan heliobi, tetapi sebaliknya ditugaskan untuk menangkap mereka dan dipercayakan dengan tugas berat untuk membasmi roh-roh keji. Meskipun dia yakin dirinya kurang mampu, dia tidak dapat mengumpulkan keberanian untuk mengundurkan diri dan terus maju meskipun berjalan di lembah ketakutannya sendiri.
                \r\nPreferensi Stats: SPD (breakpoint) > HP% > Effect RES% = DEF%
                Prioritas Skill: Ultimate >= Skill = Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "S+",
                'lightcone_sign_id' => 52,
                'lightcone_alt1_id' => 71,
                'lightcone_alt2_id' => 64,
                'relic_opt1_id' => 12,
                'relic_opt2_id' => 10,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Huohuo.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Jing Yuan",
                'path' => "Erudition",
                'element' => "Lightning",
                'role' => "DPS",
                'detail' => "Salah satu dari tujuh Jenderal Penengah dari Ksatria Awan Aliansi Xianzhou, dan salah satu dari Enam Kusir Xianzhou Luofu.Meskipun dia terlihat malas, Jing Yuan telah menjadi jenderal di Luofu selama berabad-abad, jumlah waktu yang melebihi sebagian besar rekan-rekannya. Hal ini dapat dikaitkan dengan kebijaksanaan dan perhatiannya pada tindakan rutin, dengan Jing Yuan lebih memilih untuk melakukan pencegahan daripada perbaikan.
                \r\nPreferensi Stats: SPD (breakpoint) = CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Talent > Skill = Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "S",
                'lightcone_sign_id' => 8,
                'lightcone_alt1_id' => 53,
                'lightcone_alt2_id' => 87,
                'relic_opt1_id' => 15,
                'relic_opt2_id' => 1,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 6,
                'image' => "Jing Yuan.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Jingliu",
                'path' => "Destruction",
                'element' => "Ice",
                'role' => "DPS",
                'detail' => "Pernah menjadi ahli pedang dari Xianzhou Luofu, serta mentor Jing Yuan. Setelah menyerah pada mara dan menjadi gila, dia berhasil melarikan diri dari Starskiff Haven pada Tahun 7380 Kalender Bintang, dan dengan mudah membekukan semua Ksatria Awan yang dikirim untuk mengejarnya sebelum akhirnya Jing Yuan menghadapi dan mengalahkannya dalam pertempuran.Namun, dia berhasil selamat dari pertemuan itu dan menjelajahi galaksi-galaksi di luar Luofu selama berabad-abad. Pada suatu titik yang tidak diketahui, Jingliu membuat kesepakatan untuk mendapatkan kembali kewarasannya, yang diusulkan oleh Luocha sebagai solusi untuk mara.
                \r\nPreferensi Stats: SPD (Breakpoint) > CRIT RATE (mencapai 50%) = CRIT DMG > ATK%
                Prioritas Skill: Skill = Talent > Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "A",
                'lightcone_sign_id' => 36,
                'lightcone_alt1_id' => 55,
                'lightcone_alt2_id' => 89,
                'relic_opt1_id' => 5,
                'relic_opt2_id' => 7,
                'planar_opt1_id' => 10,
                'planar_opt2_id' => 4,
                'image' => "Jingliu.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kafka",
                'path' => "Nihility",
                'element' => "Lightning",
                'role' => "Sub-DPS",
                'detail' => "Seorang anggota Pemburu Stellaron yang tenang, tenang, dan cantik. Catatannya dalam daftar buronan Interastral Peace Corporation hanya mencantumkan namanya dan hobinya. Orang-orang selalu membayangkannya sebagai sosok yang anggun, terhormat, dan mengejar hal-hal yang indah bahkan dalam pertempuran.
                \r\nPreferensi Stats: SPD (breakpoint) = EHR  > ATK% > Break Effect
                Prioritas Skill: Ultimate > Skill > Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "S",
                'lightcone_sign_id' => 60,
                'lightcone_alt1_id' => 33,
                'lightcone_alt2_id' => 27,
                'relic_opt1_id' => 14,
                'relic_opt2_id' => 1,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 12,
                'image' => "Kafka.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Luka",
                'path' => "Nihility",
                'element' => "Physical",
                'role' => "Sub-DPS",
                'detail' => "Anggota Wildfire yang optimis dan tanpa beban. Dia adalah juara tinju terkenal di Belobog Underworld dengan keahlian bela diri campuran. Antusiasmenya menginspirasi orang lain, terutama anak-anak, untuk bermimpi besar.
                \r\nPreferensi Stats: SPD (breakpoint) = EHR > Break Effect >= ATK%
                Prioritas Skill: Skill > Talent > Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "A",
                'tier_pf' => "D",
                'lightcone_sign_id' => 33,
                'lightcone_alt1_id' => 60,
                'lightcone_alt2_id' => 27,
                'relic_opt1_id' => 14,
                'relic_opt2_id' => 16,
                'planar_opt1_id' => 14,
                'planar_opt2_id' => 4,
                'image' => "Luka.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Luocha",
                'path' => "Abundance",
                'element' => "Imaginary",
                'role' => "Sustain",
                'detail' => "Seorang pedagang asing yang datang dari seberang lautan, dia muncul di Xianzhou Luofu dengan peti mati yang sangat besar. Dengan kemampuan medisnya yang sempurna, dia selalu menyelamatkan orang di saat bahaya. Sebagai seorang pedagang, dia terdaftar di Xianzhou Yuque dalam Aliansi, dan di cabang Star Unity Mall di North Valley Star dalam Interastral Peace Corporation.
                \r\nPreferensi Stats: SPD (breakpoint) > ATK% > DEF% = HP% > Effect RES%
                Prioritas Skill: Talent >= Skill > Ultimate = Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "A",
                'lightcone_sign_id' => 26,
                'lightcone_alt1_id' => 52,
                'lightcone_alt2_id' => 61,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 12,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Luocha.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Lynx",
                'path' => "Abundance",
                'element' => "Quantum",
                'role' => "Sustain",
                'detail' => "Putri bungsu dari Keluarga Landau, ia adalah seorang penjelajah lingkungan yang terkenal meskipun ia adalah seorang gadis yang tertutup.
                \r\nPreferensi Stats: SPD (breakpoint) > HP% > Effect RES% = DEF%
                Prioritas Skill: Ultimate > Talent >= Skill = Basic",
                'rarity' => "4star",
                'tier_moc' => "A",
                'tier_pf' => "B",
                'lightcone_sign_id' => 52,
                'lightcone_alt1_id' => 86,
                'lightcone_alt2_id' => 64,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 12,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Lynx.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "March 7th",
                'path' => "Preservation",
                'element' => "Ice",
                'role' => "Sustain",
                'detail' => "Seorang gadis yang antusias yang diselamatkan dari es abadi oleh Kru Astral Express, dan memiliki kemampuan unik untuk dapat menggunakan Es Bertahap Enam. Ketika dia terbangun, dia tidak tahu apa-apa tentang dirinya sendiri atau masa lalunya, dan memutuskan untuk menamai dirinya sendiri dengan nama tanggal kelahirannya, 7 Maret. Dia mengambil banyak foto menggunakan kameranya dengan harapan dapat menemukan kenang-kenangan dari masa lalunya.
                \r\nPreferensi Stats: EHR (Hingga 64% atau abaikan jika tidak memakai freeze build) = SPD (breakpoint) > DEF% > HP% = Effect RES%
                Prioritas Skill: Skill > Ultimate = Talent = Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "C",
                'lightcone_sign_id' => 49,
                'lightcone_alt1_id' => 73,
                'lightcone_alt2_id' => 43,
                'relic_opt1_id' => 8,
                'relic_opt2_id' => 10,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "March 7th.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Misha",
                'path' => "Destruction",
                'element' => "Ice",
                'role' => "DPS",
                'detail' => "Seorang pelayan yang ramah dan penuh perhatian di The Reverie Hotel. Dia ingin menjadi petualang antar galaksi seperti kakeknya. Dia sangat pekerja keras dan terampil dalam memperbaiki berbagai mesin. Dia juga suka berbagi rumor antarbintang dengan para tamu. Dia berharap bisa tumbuh lebih cepat dan tidak sabar untuk memulai perjalanan menjelajah bintangnya sendiri.
                \r\nPreferensi Stats: SPD (Breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Ultimate = Skill > Talent > Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "C",
                'lightcone_sign_id' => 55,
                'lightcone_alt1_id' => 82,
                'lightcone_alt2_id' => 89,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 7,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 10,
                'image' => "Misha.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Natasha",
                'path' => "Preservation",
                'element' => "Physical",
                'role' => "Sustain",
                'detail' => "Teliti dan baik hati, dia adalah salah satu dari sedikit dokter dari Dunia Bawah yang memiliki sumber daya medis yang langka. Kemudian terungkap bahwa Natasha adalah pemimpin Wildfire yang sebenarnya, dengan Oleg sebagai pemimpin sementara.
                \r\nPreferensi Stats: SPD (breakpoint) > HP% > Effect RES% = DEF%
                Prioritas Skill: Ultimate > Skill > Talent > Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "C",
                'lightcone_sign_id' => 52,
                'lightcone_alt1_id' => 86,
                'lightcone_alt2_id' => 64,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 12,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Natasha.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Pela",
                'path' => "Nihility",
                'element' => "Ice",
                'role' => "Support",
                'detail' => "Dikagumi oleh Pengawal Silvermane, dia adalah Perwira Intelijen yang menangani urusan mereka. Dia dapat menanggapi masalah apa pun dengan jaminan yang tenang.
                \r\nPreferensi Stats: EHR% = SPD (breakpoint) > HP = DEF > Effect RES% (30% Jika menggunakan Broken keel)
                Prioritas Skill: Ultimate >= Talent > Skill = Basic",
                'rarity' => "4star",
                'tier_moc' => "A",
                'tier_pf' => "S",
                'lightcone_sign_id' => 67,
                'lightcone_alt1_id' => 39,
                'lightcone_alt2_id' => 9,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 6,
                'planar_opt1_id' => 9,
                'planar_opt2_id' => 2,
                'image' => "Pela.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Qingque",
                'path' => "Erudition",
                'element' => "Quantum",
                'role' => "DPS",
                'detail' => "Seorang peramal dari Komisi Ramalan di Xianzhou Luofu, dan seorang pustakawan. Dia tidak pernah bermalas-malasan dan akan segera diturunkan pangkatnya menjadi penjaga pintu.
                \r\nPreferensi Stats: SPD (breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Basic > Skill = Talent > Ultimate",
                'rarity' => "4star",
                'tier_moc' => "S",
                'tier_pf' => "B",
                'lightcone_sign_id' => 53,
                'lightcone_alt1_id' => 32,
                'lightcone_alt2_id' => 8,
                'relic_opt1_id' => 5,
                'relic_opt2_id' => 11,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 10,
                'image' => "Qingque.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Ruan Mei",
                'path' => "Harmony",
                'element' => "Ice",
                'role' => "Support",
                'detail' => "Seorang ahli dalam ilmu biologi. Dia menarik perhatian Nous dengan bakat dan ketekunannya yang luar biasa, dan memulai penelitiannya tentang asal mula kehidupan di sudut rahasia alam semesta. Karena itu, dia diundang oleh Herta untuk berkolaborasi dengan Screwllum dan Stephen untuk mengembangkan Simulated Universe.
                Diam-diam, dia sangat menikmati teater tradisional dan makanan penutup, dan dia juga sangat tertarik dengan sulaman.
                \r\nPreferensi Stats: Break Effect% (mencapai 180%) > SPD (Breakpoint) > HP% = DEF% > Effect RES% (30% Jika menggunakan Broken Keel)
                Prioritas Skill: Ultimate = Talent = Skill > Basic",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "S+",
                'lightcone_sign_id' => 58,
                'lightcone_alt1_id' => 47,
                'lightcone_alt2_id' => 48,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 16,
                'planar_opt1_id' => 5,
                'planar_opt2_id' => 2,
                'image' => "Ruan Mei.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Sampo",
                'path' => "Nihility",
                'element' => "Wind",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah tentara bayaran yang fasih dari Dunia Bawah yang melakukan segala macam pekerjaan untuk pelanggannya, selama dia tidak dibayar dengan harga yang lebih tinggi.
                \r\nPreferensi Stats: SPD (breakpoint) = EHR > ATK% > Break Effect%
                Prioritas Skill: Talent > Skill > Ultimate > Basic",
                'rarity' => "4star",
                'tier_moc' => "A",
                'tier_pf' => "A",
                'lightcone_sign_id' => 33,
                'lightcone_alt1_id' => 27,
                'lightcone_alt2_id' => 42,
                'relic_opt1_id' => 14,
                'relic_opt2_id' => 13,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 8,
                'image' => "Sampo.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Seele",
                'path' => "The Hunt",
                'element' => "Quantum",
                'role' => "DPS",
                'detail' => "Anggota kunci Wildfire yang bersemangat dan gagah berani yang tumbuh di Dunia Bawah Belobog yang berbahaya. Ia terbiasa hidup sendirian. Seperti julukannya Babochka (bahasa Rusia: Бабочка Babochka, Kupu-kupu), ia melayang-layang di medan perang dengan anggun sambil menyebabkan badai.
                \r\nPreferensi Stats: CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Talent = Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "A",
                'lightcone_sign_id' => 38,
                'lightcone_alt1_id' => 78,
                'lightcone_alt2_id' => 56,
                'relic_opt1_id' => 5,
                'relic_opt2_id' => 13,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 10,
                'image' => "Seele.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Serval",
                'path' => "Erudition",
                'element' => "Lightning",
                'role' => "DPS",
                'detail' => "Dia adalah putri sulung dari keluarga Landau dan seorang mekanik yang menjalankan Neverwinter Workshop, sebuah bengkel pertunjukan rock 'n' roll di Belobog sebagai hobi.
                \r\nPreferensi Stats: SPD (breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Talent > Ultimate > Basic",
                'rarity' => "4star",
                'tier_moc' => "B",
                'tier_pf' => "A",
                'lightcone_sign_id' => 53,
                'lightcone_alt1_id' => 32,
                'lightcone_alt2_id' => 5,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 1,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 12,
                'image' => "Serval.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Silver Wolf",
                'path' => "Nihility",
                'element' => "Quantum",
                'role' => "Support",
                'detail' => "Seorang anggota Pemburu Stellaron dan peretas jenius. Silver Wolf telah menguasai keterampilan yang dikenal sebagai pengeditan aether, yang dapat digunakan untuk mengutak-atik data realitas. Oleh karena itu, dia selalu memandang alam semesta sebagai permainan simulasi yang sangat mendalam dan ingin sekali menyelesaikan tahapan yang menanti di depan.
                \r\nPreferensi Stats: EHR% = SPD (breakpoint) > HP = DEF = Break Effect% > Effect RES% (30% Jika menggunakan Broken Keel)
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "C",
                'lightcone_sign_id' => 67,
                'lightcone_alt1_id' => 9,
                'lightcone_alt2_id' => 39,
                'relic_opt1_id' => 5,
                'relic_opt2_id' => 10,
                'planar_opt1_id' => 9,
                'planar_opt2_id' => 2,
                'image' => "Silver Wolf.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Sparkle",
                'path' => "Harmony",
                'element' => "Quantum",
                'role' => "Support",
                'detail' => "Seorang anggota dari Orang-Orang Bodoh Bertopeng. Tidak bisa ditebak dan tidak bermoral. Seorang ahli sandiwara yang berbahaya yang asyik bermain peran. Seorang wanita dengan banyak topeng dan banyak wajah. Kekayaan, status, kekuasaan... Tak satu pun dari semua ini penting bagi Sparkle. Satu-satunya hal yang dapat menarik minatnya adalah hiburan.
                \r\nPreferensi Stats: SPD (breakpoint atau sebanyak mungkin) > CRIT DMG% > HP = DEF = Effect RES% (30% Jika menggunakan Broken Keel)
                Prioritas Skill: Skill > Ultimate = Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "S+",
                'tier_pf' => "S+",
                'lightcone_sign_id' => 25,
                'lightcone_alt1_id' => 11,
                'lightcone_alt2_id' => 59,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 3,
                'planar_opt1_id' => 2,
                'planar_opt2_id' => 5,
                'image' => "Sparkle.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Sushang",
                'path' => "The Hunt",
                'element' => "Physical",
                'role' => "Sub-DPS",
                'detail' => "Seorang Ksatria Awan amatir di kapal Xianzhou Luofu yang dipindahkan dari Xianzhou Yaoqing. Dia bercita-cita untuk menjadi sosok yang terkenal, tetapi kesulitan dengan bahasa.
                \r\nPreferensi Stats: SPD (breakpoint) > Break Effect% (Jika membuat Break Build) >= CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "D",
                'lightcone_sign_id' => 78,
                'lightcone_alt1_id' => 38,
                'lightcone_alt2_id' => 56,
                'relic_opt1_id' => 2,
                'relic_opt2_id' => 13,
                'planar_opt1_id' => 10,
                'planar_opt2_id' => 4,
                'image' => "Sushang.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Tingyun",
                'path' => "Harmony",
                'element' => "Lightning",
                'role' => "Support",
                'detail' => "Dia adalah seorang pemuda Rubah dan duta besar dari Komisi Penerbangan Langit Xianzhou Luofu.Dia diungkapkan sebagai kapal Lord Ravager Phantylia dalam Misi Perintis Jalan Terjal Kedalaman Keputusasaan, dan diasumsikan telah meninggal pada saat Obsequies Performed, A Long Road Ahead.
                \r\nPreferensi Stats: SPD (Breakpoint) = ATK% > HP = DEF > Effect RES% (30% Jika menggunakan Broken Keel)
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "4star",
                'tier_moc' => "S",
                'tier_pf' => "S",
                'lightcone_sign_id' => 18,
                'lightcone_alt1_id' => 48,
                'lightcone_alt2_id' => 47,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 11,
                'planar_opt1_id' => 2,
                'planar_opt2_id' => 9,
                'image' => "Tingyun.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Topaz and Numby",
                'path' => "The Hunt",
                'element' => "Fire",
                'role' => "Sub-DPS",
                'detail' => "Topaz adalah Manajer Senior Departemen Investasi Strategis di Interastral Peace Corporation, salah satu dari Sepuluh Hati Batu, dan pemimpin Tim Piket Utang Khusus.
                Mitra Topaz, Warp Trotter Numby, juga mampu merasakan dengan tajam di mana kekayaan berada. Ia bahkan dapat melakukan pekerjaan yang melibatkan keamanan, penagihan utang, dan ilmu aktuaria.
                \r\nPreferensi Stats: SPD (breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill >= Talent > Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "S",
                'tier_pf' => "B",
                'lightcone_sign_id' => 96,
                'lightcone_alt1_id' => 78,
                'lightcone_alt2_id' => 56,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 15,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 6,
                'image' => "Topaz and Numby.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Trailblazer (Destruction)",
                'path' => "Destruction",
                'element' => "Physical",
                'role' => "DPS",
                'detail' => "Mereka dibangunkan selama acara pembukaan permainan oleh Kafka dan Silver Wolf, yang meninggalkan mereka untuk ditemukan oleh 7 Maret dan Dan Heng di Stasiun Luar Angkasa Herta selama invasi Legiun Antimateri. Pemain dapat memilih Stelle (perempuan) atau Caelus (laki-laki), bersama dengan nama kode wadah mereka.
                \r\nPreferensi Stats: SPD (breakpoint) > Break Effect% (Jika membuat Break Build) >= CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "D",
                'tier_pf' => "C",
                'lightcone_sign_id' => 55,
                'lightcone_alt1_id' => 89,
                'lightcone_alt2_id' => 82,
                'relic_opt1_id' => 2,
                'relic_opt2_id' => 13,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 10,
                'image' => "Trailblazer (Destruction).png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Trailblazer (Preservation)",
                'path' => "Preservation",
                'element' => "Fire",
                'role' => "Sub-DPS",
                'detail' => "Mereka dibangunkan selama acara pembukaan permainan oleh Kafka dan Silver Wolf, yang meninggalkan mereka untuk ditemukan oleh 7 Maret dan Dan Heng di Stasiun Luar Angkasa Herta selama invasi Legiun Antimateri. Pemain dapat memilih Stelle (perempuan) atau Caelus (laki-laki), bersama dengan nama kode wadah mereka.
                \r\nPreferensi Stats: Effect RES until 30% (Jika menggunakan Broken Keel) > SPD > DEF% > HP% > Effect Hit Rate
                Prioritas Skill: Ultimate > Talent > Basic > Skill",
                'rarity' => "5star",
                'tier_moc' => "C",
                'tier_pf' => "A",
                'lightcone_sign_id' => 49,
                'lightcone_alt1_id' => 43,
                'lightcone_alt2_id' => 73,
                'relic_opt1_id' => 8,
                'relic_opt2_id' => 10,
                'planar_opt1_id' => 2,
                'planar_opt2_id' => 5,
                'image' => "Trailblazer (Preservation).png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Welt",
                'path' => "Nihility",
                'element' => "Imaginary",
                'role' => "Sub-DPS",
                'detail' => "Sebagai seorang animator, Welt adalah anggota berpengalaman dari Kru Astral Express dan mantan penguasa Anti-Entropi yang telah berkali-kali menyelamatkan Bumi dari kemusnahan. Dia mewarisi nama dunia, Welt.
                \r\nPreferensi Stats: SPD (breakpoint) = EHR% > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Talent > Ultimate > Basic",
                'rarity' => "5star",
                'tier_moc' => "B",
                'tier_pf' => "B",
                'lightcone_sign_id' => 39,
                'lightcone_alt1_id' => 33,
                'lightcone_alt2_id' => 37,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 17,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 8,
                'image' => "Welt.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Xueyi",
                'path' => "Destruction",
                'element' => "Quantum",
                'role' => "Sub-DPS",
                'detail' => "Salah satu hakim dari Komisi Sepuluh Hakim. Dari empat tugas hakim (penahanan, interogasi, penahanan, dan hukuman), dia ditugaskan untuk melakukan penahanan.
                Dengan memegang rantai besi dan Marasunder Awl di tangannya, dia tanpa lelah melacak penjahat yang dicari dan menundukkan mereka.
                \r\nPreferensi Stats: SPD (breakpoint) > Break Effect% >= CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill = Talent > Ultimate > Basic",
                'rarity' => "4star",
                'tier_moc' => "A",
                'tier_pf' => "B",
                'lightcone_sign_id' => 55,
                'lightcone_alt1_id' => 82,
                'lightcone_alt2_id' => 89,
                'relic_opt1_id' => 5,
                'relic_opt2_id' => 16,
                'planar_opt1_id' => 14,
                'planar_opt2_id' => 4,
                'image' => "Xueyi.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yanqing",
                'path' => "The Hunt",
                'element' => "Ice",
                'role' => "DPS",
                'detail' => "Letnan termuda dari Ksatria Awan Aliansi Xianzhou di kapal Xianzhou Luofu, dan punggawa Jenderal Jing Yuan. Seorang pendekar pedang yang berbakat dalam seni bermain pedang dan perang yang memiliki minat luar biasa terhadap pedang dan selalu mengumpulkannya dari Komisi Pengrajin.
                \r\nPreferensi Stats: SPD (breakpoint) > CRIT RATE = CRIT DMG > ATK%
                Prioritas Skill: Skill > Ultimate > Talent > Basic",
                'rarity' => "5star",
                'tier_moc' => "C",
                'tier_pf' => "D",
                'lightcone_sign_id' => 38,
                'lightcone_alt1_id' => 78,
                'lightcone_alt2_id' => 56,
                'relic_opt1_id' => 13,
                'relic_opt2_id' => 7,
                'planar_opt1_id' => 4,
                'planar_opt2_id' => 10,
                'image' => "Yanqing.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yukong",
                'path' => "Harmony",
                'element' => "Imaginary",
                'role' => "Support",
                'detail' => "Helm Master yang berpengalaman dan berwibawa dari Komisi Penerbangan Langit Aliansi Xianzhou dan salah satu dari Enam Kusir Xianzhou Luofu. Meskipun memiliki prestasi dalam mengemudikan kapal terbang, dia tidak lagi terbang karena pertempuran yang brutal.
                \r\nPreferensi Stats: SPD > HP = DEF > EFF RES% (30% Jika menggunakan Broken Keel)
                Prioritas Skill: Skill > Ultimate > Talent = Basic",
                'rarity' => "4star",
                'tier_moc' => "C",
                'tier_pf' => "C",
                'lightcone_sign_id' => 63,
                'lightcone_alt1_id' => 47,
                'lightcone_alt2_id' => 11,
                'relic_opt1_id' => 10,
                'relic_opt2_id' => 9,
                'planar_opt1_id' => 2,
                'planar_opt2_id' => 5,
                'image' => "Yukong.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
