<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterGenshinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('character_genshins')->insert([
            [
                'name' => "Furina",
                'type' => "Sword",
                'element' => "Hydro",
                'role' => "Sub-DPS",
                'detail' => "Diperkenalkan sebagai Hydro Archon yang flamboyan dan terlalu percaya diri, sandiwara Furina pada akhirnya terungkap sebagai persona publik, yang kemudian dibuangnya untuk menjalani kehidupan yang relatif lebih rendah hati sebagai aktris dan konsultan artistik.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > HP%
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 1,
                'weapon_alt1_genshin_id' => 23,
                'weapon_alt2_genshin_id' => 25,
                'artifact_opt1_id' => 2,
                'artifact_opt2_id' => 42,
                'image' => "Furina.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Albedo",
                'type' => "Sword",
                'element' => "Geo",
                'role' => "Sub-DPS",
                'detail' => "Manusia sintetis yang dibuat oleh alkemis Rhinedottir, Albedo yang misterius adalah Kepala Alkemis dan Kapten Tim Investigasi Ksatria Favonius.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > DEF% > ATK% > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 21,
                'weapon_alt1_genshin_id' => 15,
                'weapon_alt2_genshin_id' => 45,
                'artifact_opt1_id' => 21,
                'artifact_opt2_id' => 29,
                'image' => "Albedo.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Alhaitham",
                'type' => "Sword",
                'element' => "Dendro",
                'role' => "Main DPS",
                'detail' => "Alhaitham adalah anggota Haravatat dari Sumeru Akademiya dan Juru Tulis Akademiya, yang bertanggung jawab untuk mendokumentasikan temuan-temuan mereka dan menyusun peraturan. Terlepas dari kecemerlangannya, orang-orang di dalam Akademiya bingung dengan Alhaitham karena keengganannya untuk bercita-cita untuk jabatan yang lebih tinggi terlepas dari egosentrisme, dan banyak yang berselisih dengannya karena pandangannya yang tidak kenal kompromi tentang rasionalitas dan kebenaran.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > Elemental Mastery > Energy Recharge > ATK%
                Prioritas Talent: Skill > Basic > Ultimate",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 13,
                'weapon_alt1_genshin_id' => 36,
                'weapon_alt2_genshin_id' => 26,
                'artifact_opt1_id' => 19,
                'artifact_opt2_id' => 11,
                'image' => "Alhaitham.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Arlecchino",
                'type' => "Polearm",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Arlecchino, juga dikenal dengan nama The Knave, Dia adalah yang Keempat dari Sebelas Harbinger Fatui dan direktur House of the Hearth saat ini. Dia dipanggil sebagai Ayah oleh para anggota rumah, yang dia sebut sebagai anak-anaknya.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 84,
                'weapon_alt1_genshin_id' => 95,
                'weapon_alt2_genshin_id' => 111,
                'artifact_opt1_id' => 17,
                'artifact_opt2_id' => 1,
                'image' => "Arlecchino.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kamisato Ayaka",
                'type' => "Sword",
                'element' => "Cryo",
                'role' => "Main DPS",
                'detail' => "Dia bertanggung jawab atas urusan internal dan eksternal Klan Kamisato dan merupakan adik dari Kamisato Ayato. Cantik, berwibawa, dan mulia, Ayaka telah mendapatkan gelar Shirasagi Himegimi dan dianggap sebagai model kesempurnaan di Inazuma.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Ultimate > Basic > Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 14,
                'weapon_alt1_genshin_id' => 36,
                'weapon_alt2_genshin_id' => 19,
                'artifact_opt1_id' => 7,
                'artifact_opt2_id' => 1,
                'image' => "Kamisato Ayaka.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Aloy",
                'type' => "Bow",
                'element' => "Cryo",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah pahlawan wanita dari Horizon Zero Dawn dan diperkenalkan sebagai karakter kolaborasi dan crossover antara Guerrilla Games dan HoYoverse.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 153,
                'weapon_alt1_genshin_id' => 169,
                'weapon_alt2_genshin_id' => 173,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Aloy.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Amber",
                'type' => "Bow",
                'element' => "Pyro",
                'role' => "Sub-DPS",
                'detail' => "Sebagai satu-satunya Outrider Ksatria Favonius yang tersisa, ia selalu siap untuk membantu warga Mondstadt - apakah itu sesuatu yang sederhana atau mungkin tugas yang lebih menantang.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 9,
                'weapon_alt1_genshin_id' => 159,
                'weapon_alt2_genshin_id' => 170,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Amber.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Arataki Itto",
                'type' => "Polearm",
                'element' => "Geo",
                'role' => "Main DPS",
                'detail' => "Sebagai keturunan oni merah yang keras dan bangga, Itto juga merupakan pemimpin dan pendiri Geng Arataki. Meskipun bukan penjahat, reputasinya sebagai penjahat di Kota Inazuma meninggalkan sesuatu yang tidak menyenangkan.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > DEF% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 50,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 76,
                'artifact_opt1_id' => 21,
                'artifact_opt2_id' => 38,
                'image' => "Arataki Itto.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Baizhu",
                'type' => "Catalyst",
                'element' => "Dendro",
                'role' => "Support",
                'detail' => "Pemilik Apotek Bubu dan wali Qiqi, Dokter Baizhu adalah seorang ahli seni pengobatan dan penerima terakhir dari kontrak generasi dengan seekor ular putih bernama Changsheng. Dia berusaha mencapai keabadian untuk memastikan bahwa dia adalah orang terakhir yang akan menanggung kontraknya, menyelamatkan calon pewaris dan bahkan Changsheng sendiri dari biaya yang timbul akibat kekuatannya.
                \r\nPreferensi Stats: Energy Recharge > HP% > HP
                Prioritas Talent: Skill = Burst",
                'rarity' => "star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 116,
                'weapon_alt1_genshin_id' => 134,
                'weapon_alt2_genshin_id' => 127,
                'artifact_opt1_id' => 11,
                'artifact_opt2_id' => 31,
                'image' => "Baizhu.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Barbara",
                'type' => "Catalyst",
                'element' => "Hydro",
                'role' => "Support",
                'detail' => "Dia adalah diakon dari Gereja Favonius dan seorang idola yang terkemuka setelah mengetahui tentang mereka dari petualang pemberani Alice. Dia juga merupakan adik perempuan dari Penjabat Grand Master Jean.
                \r\nPreferensi Stats: HP% > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 145,
                'weapon_alt1_genshin_id' => 134,
                'weapon_alt2_genshin_id' => 127,
                'artifact_opt1_id' => 25,
                'artifact_opt2_id' => 31,
                'image' => "Barbara.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Beidou",
                'type' => "Polearm",
                'element' => "Electro",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah kapten The Crux, sebuah kru yang terkenal di Liyue. Selain kemampuannya sebagai kapten armada dan kekuatannya yang luar biasa, banyak orang di Liyue mengenalnya karena kurangnya rasa takutnya terhadap Tianquan dari Liyue Qixing, Ningguang - sebuah sifat yang dihargai oleh yang lain, namun menjadi jengkel karenanya.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 55,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 57,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 29,
                'image' => "Beidou.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Bennett",
                'type' => "Sword",
                'element' => "Pyro",
                'role' => "Support",
                'detail' => "Sebagai anak yatim piatu yang ditemukan oleh seorang petualang tua saat masih bayi, Bennett dibesarkan di Persekutuan Petualang Mondstadt. Dia adalah satu-satunya anggota Tim Petualangan Benny, karena semua orang meninggalkan tim setelah mengalami kemalangan yang terus-menerus mengikutinya.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 5,
                'weapon_alt1_genshin_id' => 35,
                'weapon_alt2_genshin_id' => 23,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Bennett.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Candace",
                'type' => "Polearm",
                'element' => "Hydro",
                'role' => "Support",
                'detail' => "Keturunan Al-Ahmar dan Penjaga Desa Aaru, Candace bersikap ramah kepada para pelancong yang berkunjung, namun tidak kenal ampun kepada mereka yang melanggar aturan desa.
                \r\nPreferensi Stats: Energy Recharge > HP%
                Prioritas Talent: (Tidak Perlu Naikan Talent)",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 99,
                'weapon_alt1_genshin_id' => 109,
                'weapon_alt2_genshin_id' => 70,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Candace.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Charlotte",
                'type' => "Catalyst",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Sebagai seorang jurnalis dari The Steambird, Charlotte selalu mencari berita eksklusif. Selalu bersemangat dan tak kenal lelah, dia tidak akan berhenti sampai dia menemukan kebenaran, bahkan jika dia mendekati bahaya.
                \r\nPreferensi Stats: Energy Recharge > ATK%
                Prioritas Talent: Ultimate",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 127,
                'weapon_alt1_genshin_id' => 134,
                'weapon_alt2_genshin_id' => 145,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Charlotte.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Chevreuse",
                'type' => "Polearm",
                'element' => "Pyro",
                'role' => "Support",
                'detail' => "Dia adalah kapten Patroli Keamanan dan Pengawasan Khusus Maison Gardiennage.
                \r\nPreferensi Stats: Energy Recharge > HP%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 99,
                'weapon_alt1_genshin_id' => 106,
                'weapon_alt2_genshin_id' => 105,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 31,
                'image' => "Chevreuse.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Chiori",
                'type' => "Sword",
                'element' => "Geo",
                'role' => "Sub-DPS",
                'detail' => "Seorang desainer independen yang berasal dari Inazuma yang berusaha untuk membuat mereknya dikenal secara internasional di seluruh Teyvat, Chiori adalah pemilik Chioriya Boutique, sebuah label fesyen di Fontaine.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > DEF% > ATK%
                Prioritas Talent: Skill > Talent",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 18,
                'weapon_alt1_genshin_id' => 21,
                'weapon_alt2_genshin_id' => 45,
                'artifact_opt1_id' => 2,
                'artifact_opt2_id' => 21,
                'image' => "Chiori.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Chongyun",
                'type' => "Claymore",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Terlahir dengan energi Yang (positif) yang berlebih, Chongyun telah menjadi pengusir setan yang sangat efektif di Liyue - begitu efektifnya sampai-sampai dia tidak pernah melihat makhluk halus, karena mereka langsung kabur ketika dia mendekat. Energi Yang yang berlebihan juga membuatnya sangat rentan terhadap panas dan emosi yang kuat, yang telah menyebabkan beberapa hasil yang tidak terduga.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 55,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 67,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Chongyun.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Collei",
                'type' => "Bow",
                'element' => "Dendro",
                'role' => "Support",
                'detail' => "Awalnya merupakan korban eksperimen manusia Fatui yang menderita Eleazar, Collei mengembara di dunia sebagai gelandangan hingga ia bertemu dengan Amber di Mondstadt. Sejak saat itu, Collei telah mengubah hidupnya, dan saat ini ia bekerja sebagai penjaga hutan di Hutan Avidya.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK% / Elemental Mastery
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 9,
                'weapon_alt1_genshin_id' => 173,
                'weapon_alt2_genshin_id' => 22,
                'artifact_opt1_id' => 11,
                'artifact_opt2_id' => 29,
                'image' => "Collei.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Cyno",
                'type' => "Polearm",
                'element' => "Electro",
                'role' => "Main DPS",
                'detail' => "Sebagai Mahamatra Umum, Cyno memimpin Matra dan memberikan rasa takut kepada para peneliti di Sumeru Akademiya. Meskipun demikian, Cyno memiliki sisi menyenangkan di luar perannya di Akademiya, karena ia memiliki ketertarikan pada Genius Invocation TCG dan selalu membuat lelucon yang lucu.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > Elemental Mastery / ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 89,
                'weapon_alt1_genshin_id' => 95,
                'weapon_alt2_genshin_id' => 111,
                'artifact_opt1_id' => 1,
                'artifact_opt2_id' => 44,
                'image' => "Cyno.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Dehya",
                'type' => "Claymore",
                'element' => "Pyro",
                'role' => "Support",
                'detail' => "Seorang pejuang yang tangguh dan kuat, Flame-Mane Dehya dianggap sebagai legenda di antara suku Eremite karena kekuatan, semangat, dan ketelitiannya. Tidak mau terjebak oleh kondisi yang memaksa sebagian besar penduduk gurun untuk tetap tinggal di sana, ia bercita-cita untuk mengembalikan harapan ke pasir yang ia anggap sebagai rumahnya.
                \r\nPreferensi Stats: HP% > ATK% > Elemental Mastery
                Prioritas Talent: Skill",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 6,
                'weapon_alt1_genshin_id' => 59,
                'weapon_alt2_genshin_id' => 70,
                'artifact_opt1_id' => 42,
                'artifact_opt2_id' => 51,
                'image' => "Dehya.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Diluc",
                'type' => "Claymore",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Terlahir dari Klan Ragnvindr yang kaya raya, Diluc adalah pemilik Kilang Anggur Fajar saat ini dan seorang bangsawan yang dihormati di Mondstadt. Meskipun sebuah insiden di masa lalu menyebabkan dia berpisah dengan Ksatria Favonius, dia terus melindungi Mondstadt dengan caranya sendiri.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Basic > Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 55,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 58,
                'artifact_opt1_id' => 10,
                'artifact_opt2_id' => 19,
                'image' => "Diluc.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Diona",
                'type' => "Bow",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Meskipun menjadi bartender di Cat's Tail, ia membenci alkohol dan tidak akan berhenti untuk merusak industri wine Mondstadt - hal yang lebih mudah diucapkan daripada dilakukan ketika para pelanggannya sangat menyukai minumannya. Dia adalah putri Draff, seorang pemburu di Springvale.
                \r\nPreferensi Stats: HP% > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 159,
                'weapon_alt1_genshin_id' => 170,
                'weapon_alt2_genshin_id' => 9,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 25,
                'image' => "Diona.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Dori",
                'type' => "Claymore",
                'element' => "Electro",
                'role' => "Support",
                'detail' => "Pemilik The Palace of Alcazarzaray dan pedagang yang sangat dihormati, Lord Sangemah Bay terkenal dengan kemampuannya untuk mendapatkan apa pun yang dibutuhkan seseorang, selama mereka memiliki cukup Mora untuk membayar harganya yang mencengangkan.
                \r\nPreferensi Stats: Energy Recharge > HP% > Elemental Mastery
                Prioritas Talent: Ultimate",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 59,
                'weapon_alt1_genshin_id' => 70,
                'weapon_alt2_genshin_id' => 61,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 43,
                'image' => "Dori.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Eula",
                'type' => "Claymore",
                'element' => "Cryo",
                'role' => "Main DPS",
                'detail' => "Meskipun merupakan keturunan dari Klan Lawrence yang terkenal kejam dan kejam, Eula memutuskan hubungannya dengan klan tersebut dan menjadi kapten Kompi Pengintai bersama Ksatria Favonius.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > Energy Recharge > ATK%
                Prioritas Talent: Ultimate > Basic > Skill",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 52,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 63,
                'artifact_opt1_id' => 32,
                'artifact_opt2_id' => 1,
                'image' => "Eula.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Faruzan",
                'type' => "Bow",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Dia adalah seorang profesor terkenal di Sumeru Akademiya dan anggota Haravatat Darshan. Dia baru-baru ini kembali ke Akademiya setelah memecahkan teka-teki dan melarikan diri dari reruntuhan yang menjebaknya seabad yang lalu.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate",
                'rarity' => "4star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 159,
                'weapon_alt1_genshin_id' => 157,
                'weapon_alt2_genshin_id' => 158,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Faruzan.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Fischl",
                'type' => "Bow",
                'element' => "Electro",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah seorang penyelidik untuk Guild Petualang Mondstadt, ditemani oleh burung gagak Oz. Seorang petualang pemberani dengan teori-teori yang tampaknya aneh yang ternyata benar, dia mengaku berasal dari dunia di luar Teyvat.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "4star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 3,
                'weapon_alt1_genshin_id' => 173,
                'weapon_alt2_genshin_id' => 166,
                'artifact_opt1_id' => 2,
                'artifact_opt2_id' => 44,
                'image' => "Fischl.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Freminet",
                'type' => "Claymore",
                'element' => "Cryo",
                'role' => "Main DPS",
                'detail' => "Terlepas dari keahlian dan pengalamannya sebagai penyelam profesional, Freminet lebih memilih untuk tidak menjadi pusat perhatian, hanya menjalankan perintah dan menemukan kedamaian di samping Bunga Tidalga dan Romaritime di bawah air.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Basic > Skill",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 51,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 74,
                'artifact_opt1_id' => 32,
                'artifact_opt2_id' => 8,
                'image' => "Freminet.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Gaming",
                'type' => "Claymore",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Lahir di Desa Qiaoying, Gaming meninggalkan tempat kelahirannya setelah berselisih dengan ayahnya untuk mengejar hasratnya dan menjadi penari Wushou profesional, berlatih secara konstan untuk membuat tarian ini populer di seluruh Teyvat. Namun, karena karier impiannya ternyata tidak berkelanjutan secara finansial, dia juga mengambil pekerjaan sebagai penjaga untuk Sword and Strongbox Secure Transport Agency, terutama mengawal barang dan orang dari dan ke Yilong Wharf. Ketekunan dan keramahannya telah membuatnya terkenal, dan dia dianggap sebagai penjaga terbaik di agensi tersebut.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > Elemental Mastery
                Prioritas Talent: Ultiamte > Basic > Skill",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 54,
                'weapon_alt1_genshin_id' => 55,
                'weapon_alt2_genshin_id' => 71,
                'artifact_opt1_id' => 10,
                'artifact_opt2_id' => 26,
                'image' => "Gaming.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Ganyu",
                'type' => "Bow",
                'element' => "Cryo",
                'role' => "Main DPS",
                'detail' => "Dia adalah seorang Adeptus setengah Qilin di bawah kontrak dengan Geo Archon Morax dan menjabat sebagai sekretaris umum Liyue Qixing.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Basic > Ultimate",
                'rarity' => "5star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 4,
                'weapon_alt1_genshin_id' => 166,
                'weapon_alt2_genshin_id' => 155,
                'artifact_opt1_id' => 4,
                'artifact_opt2_id' => 40,
                'image' => "Ganyu.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Gorou",
                'type' => "Bow",
                'element' => "Geo",
                'role' => "Support",
                'detail' => "Dia adalah seorang jenderal Angkatan Darat Watatsumi. Berani dan dapat diandalkan, anak buahnya tahu bahwa mereka dapat menaruh kepercayaan padanya baik di dalam maupun di luar medan perang.
                \r\nPreferensi Stats: Energy Recharge > DEF% > CRIT Rate
                Prioritas Talent: Skill",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 159,
                'weapon_alt1_genshin_id' => 170,
                'weapon_alt2_genshin_id' => 178,
                'artifact_opt1_id' => 43,
                'artifact_opt2_id' => 29,
                'image' => "Gorou.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Hu Tao",
                'type' => "Polearm",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Kejenakaan dan keeksentrikan Hu Tao mengingkari perannya sebagai Direktur ke-77 Rumah Duka Wangsheng dan bakatnya sebagai penyair. Namun demikian, dia memperlakukan operasi rumah duka dengan sangat penting, dan mengadakan upacara pemakaman dengan martabat dan kesungguhan tertinggi.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > Elemental Mastery > HP%
                Prioritas Talent: Skill > Basic > Ultimate",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 88,
                'weapon_alt1_genshin_id' => 97,
                'weapon_alt2_genshin_id' => 95,
                'artifact_opt1_id' => 10,
                'artifact_opt2_id' => 40,
                'image' => "Hu Tao.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Jean",
                'type' => "Sword",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Kakak perempuan dari Barbara, dan keturunan dari Klan Gunnhildr yang bergengsi, Jean adalah Penjabat Grand Master Ksatria Favonius. Dia selalu sibuk menangani kerusuhan di seluruh Mondstadt dan tanpa lelah bekerja untuk mempertahankan Kota Kebebasan.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 15,
                'weapon_alt1_genshin_id' => 22,
                'weapon_alt2_genshin_id' => 19,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Jean.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kaedehara Kazuha",
                'type' => "Sword",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Seorang samurai pengembara dari Klan Kaedehara yang dulu terkenal dengan kemampuan membaca suara alam, Kazuha adalah anggota kru sementara The Crux. Meskipun terbebani oleh banyak kejadian di masa lalunya, Kazuha masih mempertahankan sifat santai.
                \r\nPreferensi Stats: Elemental Mastery > Energy Recharge
                Prioritas Talent: (Tidak Perlu Naikan Talent)",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 10,
                'weapon_alt1_genshin_id' => 26,
                'weapon_alt2_genshin_id' => 22,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 22,
                'image' => "Kaedehara Kazuha.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kaeya",
                'type' => "Sword",
                'element' => "Cryo",
                'role' => "Sub-DPS",
                'detail' => "Kaeya adalah Kapten Kavaleri Ksatria Favonius. Dia sangat dihormati oleh masyarakat Mondstadt - bahkan dengan segala keanehan dan rahasianya.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 15,
                'weapon_alt1_genshin_id' => 23,
                'weapon_alt2_genshin_id' => 31,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 29,
                'image' => "Kaeya.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kamisato Ayato",
                'type' => "Sword",
                'element' => "Hyrdro",
                'role' => "Main DPS",
                'detail' => "Dia adalah kepala Klan Kamisato saat ini, kakak dari Kamisato Ayaka, dan Komisaris Yashiro. Banyak akal dan licik, Ayato menjaga profil yang lebih rendah daripada saudara perempuannya dan berfokus pada urusan pemerintahan di Komisi.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 11,
                'weapon_alt1_genshin_id' => 14,
                'weapon_alt2_genshin_id' => 36,
                'artifact_opt1_id' => 20,
                'artifact_opt2_id' => 1,
                'image' => "Kamisato Ayato.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kaveh",
                'type' => "Claymore",
                'element' => "Dendro",
                'role' => "Main DPS",
                'detail' => "Arsitek di balik Istana Alcazarzaray, Kaveh adalah seorang siswa Kshahrewar Darshan dari Sumeru Akademiya dan lulus dengan predikat kehormatan, sehingga mendapatkan julukan Cahaya Kshahrewar. Setelah bangkrut setelah pembangunan Istana Alcazarzaray, ia terpaksa tinggal bersama Alhaitham, yang memiliki hubungan yang rumit dengannya. Terlepas dari fasad termasyhur yang ia pertahankan untuk orang luar, Kaveh sering kali dibebani rasa bersalah atas kematian ayahnya, malu akan kemiskinannya, dan berjuang untuk mewujudkan cita-citanya.
                \r\nPreferensi Stats: Energy Recharge > Elemental Mastery > Crit Rate
                Prioritas Talent: Basic > Skill",
                'rarity' => "4star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 59,
                'weapon_alt1_genshin_id' => 70,
                'weapon_alt2_genshin_id' => 64,
                'artifact_opt1_id' => 11,
                'artifact_opt2_id' => 16,
                'image' => "Kaveh.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Keqing",
                'type' => "Sword",
                'element' => "Electro",
                'role' => "Main DPS",
                'detail' => "Sebagai Yuheng dari Liyue Qixing, dia adalah seseorang yang mencari jawabannya sendiri dan bukannya diam saja membiarkan kekacauan terjadi di Liyue. Dia memilih jalannya sendiri dengan kekuatan dan kemampuannya sendiri, alih-alih membiarkan para dewa menentukan nasibnya.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 14,
                'weapon_alt1_genshin_id' => 28,
                'weapon_alt2_genshin_id' => 36,
                'artifact_opt1_id' => 44,
                'artifact_opt2_id' => 45,
                'image' => "Keqing.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kirara",
                'type' => "Sword",
                'element' => "Dendro",
                'role' => "Support",
                'detail' => "Seorang youkai - nekomata, tepatnya - Kirara adalah Kurir Tingkat Emas dari Komaniya Express yang berbasis di Inazuma. Ketekunannya dalam memastikan setiap paket dikirim ke tempat yang tepat telah meningkatkan reputasi perusahaan dan dirinya, menjadikannya satu-satunya kurir yang menangani pengiriman internasional.[5] Dia menikmati setiap pengiriman yang dilakukannya karena dia menganggapnya sebagai tamasya untuk dirinya sendiri.
                \r\nPreferensi Stats: Energy Rechage > HP%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 22,
                'weapon_alt1_genshin_id' => 31,
                'weapon_alt2_genshin_id' => 23,
                'artifact_opt1_id' => 11,
                'artifact_opt2_id' => 29,
                'image' => "Kirara.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Klee",
                'type' => "Catalyst",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Putri dari petualang pemberani dan sering kali cukup merusak, Alice, Klee meniru ibunya dalam banyak hal, yang membuat para Ksatria Favonius yang dipercayakan kepadanya merasa cemas.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 118,
                'weapon_alt1_genshin_id' => 139,
                'weapon_alt2_genshin_id' => 138,
                'artifact_opt1_id' => 10,
                'artifact_opt2_id' => 4,
                'image' => "Klee.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kujou Sara",
                'type' => "Bow",
                'element' => "Electro",
                'role' => "Support",
                'detail' => "Sebagai seorang tengu, Sara adalah putri angkat Klan Kujou dari Komisi Tenryou. Setia kepada klannya dan Shogun, Sara melaksanakan perintahnya sesuai dengan kehendak Shogun.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 152,
                'weapon_alt1_genshin_id' => 164,
                'weapon_alt2_genshin_id' => 170,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 29,
                'image' => "Kujou Sara.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Kuki Shinobu",
                'type' => "Sword",
                'element' => "Electro",
                'role' => "Sub-DPS",
                'detail' => "Seorang mantan gadis kuil di Kuil Agung Narukami, ia adalah sahabat karib Arataki Itto dan Wakil Pemimpin Geng Arataki. Berkat profesionalisme dan sertifikasinya, Kuki Shinobu telah membantu Geng Arataki keluar dari banyak masalah, dan bahkan telah memperluas cakupan bisnis geng di luar kenakalan dan kenakalan biasa.
                \r\nPreferensi Stats: Elemental Mastery > HP%
                Prioritas Talent: Skill",
                'rarity' => "4star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 10,
                'weapon_alt1_genshin_id' => 26,
                'weapon_alt2_genshin_id' => 41,
                'artifact_opt1_id' => 16,
                'artifact_opt2_id' => 19,
                'image' => "Kuki Shinobu.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Layla",
                'type' => "Sword",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Ia adalah seorang mahasiswa di Darshan Rtawahist, yang mengkhususkan diri dalam Astrologi Teoritis. Kurang tidur secara kronis dan kesehatan yang buruk sebagai akibatnya, Layla percaya bahwa Berkah Bintang adalah alasan dia terbangun dari tidur dan mendapati kertas-kertasnya telah selesai dikerjakan.
                \r\nPreferensi Stats: HP% > Energy Recharge > CRIT Rate / CRIT DMG
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 12,
                'weapon_alt1_genshin_id' => 22,
                'weapon_alt2_genshin_id' => 45,
                'artifact_opt1_id' => 42,
                'artifact_opt2_id' => 29,
                'image' => "Layla.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Lisa",
                'type' => "Catalyst",
                'element' => "Electro",
                'role' => "Sub-DPS",
                'detail' => "Seorang penyihir tangguh yang diakui sebagai lulusan Sumeru Akademiya yang paling terhormat dalam 200 tahun terakhir, Lisa telah kembali ke Mondstadt untuk menjadi Pustakawan Ksatria Favonius yang rendah hati.
                \r\nPreferensi Stats: Energy Rechare > CRIT Rate / CRIT DMG > Elemental Mastery
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 117,
                'weapon_alt1_genshin_id' => 139,
                'weapon_alt2_genshin_id' => 132,
                'artifact_opt1_id' => 44,
                'artifact_opt2_id' => 19,
                'image' => "Lisa.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Lynette",
                'type' => "Sword",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Pendiam dan pendiam, Lynette berfungsi sebagai asisten penyihir untuk kakaknya, Lyney. Setelah kematian orang tua mereka dan setelah diselamatkan dari seorang bangsawan yang kejam oleh Ayah mereka, Lynette juga berfungsi sebagai mata dan telinga bagi House of the Hearth.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 31,
                'weapon_alt1_genshin_id' => 22,
                'weapon_alt2_genshin_id' => 25,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Lynette.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Lyney",
                'type' => "Bow",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Terampil dan fasih, Lyney adalah Penyihir Hebat Fontaine dan saudara kembar Lynette. Setelah kematian orang tua mereka dan setelah diselamatkan dari seorang bangsawan yang kejam oleh Ayah mereka, Lyney telah menjalankan misi untuk House of the Hearth dan mengatakan bahwa dia pada akhirnya akan menjadi penerus Ayah.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 151,
                'weapon_alt1_genshin_id' => 3,
                'weapon_alt2_genshin_id' => 166,
                'artifact_opt1_id' => 26,
                'artifact_opt2_id' => 49,
                'image' => "Lyney.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Mika",
                'type' => "Polearm",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Adik dari Huffman dan surveyor garis depan dari Knights of Favonius Reconnaissance Company yang dipimpin oleh Eula, Mika dengan tekun melaksanakan semua tugasnya secara efisien dan bermimpi untuk menjadi kartografer ahli di masa depan. Meskipun dia pemalu terhadap orang lain, dia akhirnya menjadi dekat dengan orang-orang yang dekat dengannya karena dia sangat menghargai kerja sama tim dan ingin belajar dari rekan-rekannya.
                \r\nPreferensi Stats: HP% > Energy Recharge
                Prioritas Talent: Skill > Ultiamte",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 99,
                'weapon_alt1_genshin_id' => 105,
                'weapon_alt2_genshin_id' => 109,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 31,
                'image' => "Mika.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Mona",
                'type' => "Catalyst",
                'element' => "Hyrdro",
                'role' => "Support",
                'detail' => "Seorang astrolog yang memiliki pengetahuan luas dan kebanggaan yang tinggi, Mona menetap di Mondstadt untuk menghindari kemarahan majikannya setelah tanpa disadari membaca buku harian majikannya.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 139,
                'weapon_alt1_genshin_id' => 132,
                'weapon_alt2_genshin_id' => 145,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 42,
                'image' => "Mona.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Nahida",
                'type' => "Catalyst",
                'element' => "Dendro",
                'role' => "Sub-DPS",
                'detail' => "Sebagai Lesser Lord Kusanali, ia berusaha untuk memiliki kehadiran yang lebih kuat di Sumeru setelah ia dibebaskan dari kungkungannya yang luas di Sanctuary of Surasthana.
                \r\nPreferensi Stats: Elemental Mastery > CRIT Rate / CRIT DMG > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 2,
                'weapon_alt1_genshin_id' => 136,
                'weapon_alt2_genshin_id' => 139,
                'artifact_opt1_id' => 11,
                'artifact_opt2_id' => 19,
                'image' => "Nahida.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Navia",
                'type' => "Claymore",
                'element' => "Geo",
                'role' => "Main DPS",
                'detail' => "Dia adalah presiden Spina di Rosula, sebuah jabatan yang sebelumnya dipegang oleh almarhum ayahnya, Callas.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Skill > Ultimate > Basic",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 54,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 67,
                'artifact_opt1_id' => 28,
                'artifact_opt2_id' => 26,
                'image' => "Navia.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Neuvillette",
                'type' => "",
                'element' => "",
                'role' => "",
                'detail' => "Neuvillette adalah Iudex dari Fontaine, dan pemimpin Phantom Marechaussee. Meskipun Neuvillette menjunjung tinggi peraturan pengadilan dengan penuh penghormatan, dia cukup menyendiri ketika berhadapan dengan emosi manusia dan sering kali menjauhkan diri dari perhatian publik. Terlepas dari penampilannya sebagai manusia, dia sebenarnya adalah Hydro Dragon Sovereign.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > HP%
                Prioritas Talent: Basic > Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 121,
                'weapon_alt1_genshin_id' => 134,
                'weapon_alt2_genshin_id' => 137,
                'artifact_opt1_id' => 26,
                'artifact_opt2_id' => 20,
                'image' => "Neuvillette.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Nilou",
                'type' => "Sword",
                'element' => "Hydro",
                'role' => "Support",
                'detail' => "Sebagai seorang penari di bawah Teater Zubayr, tarian Nilou sangat elegan dan anggun - namun, di luar sorotan panggung, ia sama seperti gadis-gadis lain seusianya; hangat, murah senyum, dan ramah.
                \r\nPreferensi Stats: HP% > Energy Recharge
                Prioritas Talent: (Tidak Perlu Naikan Talent)",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 12,
                'weapon_alt1_genshin_id' => 22,
                'weapon_alt2_genshin_id' => 41,
                'artifact_opt1_id' => 42,
                'artifact_opt2_id' => 11,
                'image' => "Nilou.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Ningguang",
                'type' => "Catalyst",
                'element' => "Geo",
                'role' => "Main DPS",
                'detail' => "Tianquan dari Liyue Qixing dan pemilik Kamar Giok yang mengambang di langit Liyue, Ningguang adalah seorang maestro yang mengguncang dasar-dasar lingkaran bisnis. Bahkan dengan mengambil beberapa potongan dari dokumen yang dia sobek dari Jade Chamber akan memberi seseorang fragmen kebijaksanaannya yang tak ternilai, cukup untuk menjauhkan diri dari rekan-rekannya.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 118,
                'weapon_alt1_genshin_id' => 125,
                'weapon_alt2_genshin_id' => 139,
                'artifact_opt1_id' => 5,
                'artifact_opt2_id' => 15,
                'image' => "Ningguang.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Noelle",
                'type' => "Claymore",
                'element' => "Geo",
                'role' => "Main DPS",
                'detail' => "Sangat kuat dan dapat diandalkan, Noelle dianggap sebagai pelayan dari segala pelayan di Ksatria Favonius, dengan banyak orang mengira dia memiliki kemampuan untuk berada di mana saja sekaligus. Namun, dia keras kepala dan bersedia membahayakan nyawanya kapan saja untuk membantu seseorang. Dia telah mencoba berkali-kali untuk bergabung dengan barisan Ksatria Favonius untuk mencapai mimpinya menjadi ksatria penuh, tetapi selalu gagal sejauh ini.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > Energy Recharge > DEF%
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 50,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 76,
                'artifact_opt1_id' => 21,
                'artifact_opt2_id' => 38,
                'image' => "Noelle.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Qiqi",
                'type' => "Sword",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Dibangkitkan sebagai zombie oleh para adepti, dia berakhir dalam perawatan Baizhu dan sekarang bekerja di Apotek Bubu di Pelabuhan Liyue.
                \r\nPreferensi Stats: ATK% > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 31,
                'weapon_alt1_genshin_id' => 27,
                'weapon_alt2_genshin_id' => 38,
                'artifact_opt1_id' => 42,
                'artifact_opt2_id' => 31,
                'image' => "Qiqi.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Raiden Shogun",
                'type' => "Polearm",
                'element' => "Electro",
                'role' => "Sub-DPS",
                'detail' => "Raiden Shogun terdiri dari dua makhluk dalam satu tubuh: Ei, Electro Archon Inazuma saat ini; dan Shogun, boneka yang diciptakan oleh Ei untuk bertindak sebagai penguasa Inazuma sebagai penggantinya.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > Energy Recharge > ATK%
                Prioritas Talent: Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 85,
                'weapon_alt1_genshin_id' => 97,
                'weapon_alt2_genshin_id' => 91,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 19,
                'image' => "Raiden Shogun.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Razor",
                'type' => "Claymore",
                'element' => "Electro",
                'role' => "Main DPS",
                'detail' => "Ditelantarkan saat masih bayi, Razor dibawa oleh Serigala Andrius Utara dan dibesarkan oleh kawanan serigalanya di Wolvendom. Setelah pertemuan kebetulan dengan Varka, Grand Master Ksatria Favonius saat ini, dia perlahan-lahan mulai berintegrasi dengan manusia lagi melalui bantuan gurunya, Lisa.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 55,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 67,
                'artifact_opt1_id' => 32,
                'artifact_opt2_id' => 1,
                'image' => "Razor.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Rosaria",
                'type' => "Polearm",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Paling tidak taat di antara para biarawati Gereja Favonius, Rosaria lebih suka bertindak dalam bayang-bayang daripada berpartisipasi dalam kegiatan Gereja.
                \r\nPreferensi Stats: CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 88,
                'weapon_alt1_genshin_id' => 91,
                'weapon_alt2_genshin_id' => 108,
                'artifact_opt1_id' => 7,
                'artifact_opt2_id' => 29,
                'image' => "Rosaria.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Sangonomiya Kokomi",
                'type' => "Catalyst",
                'element' => "Hydro",
                'role' => "Support",
                'detail' => "Pendeta wanita muda di Pulau Watatsumi dan keturunan Klan Sangonomiya, Kokomi bertanggung jawab atas sebagian besar urusan Watatsumi, memikul tanggung jawab yang berat seorang diri dengan harapan dapat memberikan harapan dan kebahagiaan kepada penduduk Pulau Watatsumi seperti yang mereka inginkan.
                \r\nPreferensi Stats: Energy Rechage > HP% > ATK%
                Prioritas Talent: Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 115,
                'weapon_alt1_genshin_id' => 145,
                'weapon_alt2_genshin_id' => 134,
                'artifact_opt1_id' => 42,
                'artifact_opt2_id' => 31,
                'image' => "Sangonomiya Kokomi.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Sayu",
                'type' => "Claymore",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Seorang ninja dari Shuumatsuban yang sedang berjuang untuk tumbuh tinggi. Sayu percaya bahwa tidur dapat membantu pertumbuhannya, dan itulah sebabnya ia lebih suka menggunakan teknik ninjanya untuk bersembunyi dan bermalas-malasan.”
                \r\nPreferensi Stats: Energy Recharge > Elemental Mastery > ATK%
                Prioritas Talent: Ultimate",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 55,
                'weapon_alt1_genshin_id' => 59,
                'weapon_alt2_genshin_id' => 70,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Sayu.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Shenhe",
                'type' => "Polearm",
                'element' => "Cryo",
                'role' => "Support",
                'detail' => "Putri dari pasangan pengusir setan yang tidak disebutkan namanya, Shenhe dibawa dan dibesarkan oleh Cloud Retainer sebagai murid setelah insiden traumatis yang dipicu oleh ayah Shenhe semasa kecilnya.
                \r\nPreferensi Stats: ATK% > Energy Recharge > CRIT Rate / CRIT DMG
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 7,
                'weapon_alt1_genshin_id' => 99,
                'weapon_alt2_genshin_id' => 91,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Shenhe.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Shikanoin Heizou",
                'type' => "Catalyst",
                'element' => "Anemo",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah detektif Komisi Tenryou nomor satu, yang memiliki persaingan dengan Sango dari Badan Detektif Bantan Sango.
                \r\nPreferensi Stats: Elemental Mastery > ATK% > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 120,
                'weapon_alt1_genshin_id' => 136,
                'weapon_alt2_genshin_id' => 132,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Shikanoin Heizou.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Sucrose",
                'type' => "Catalyst",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Seorang alkemis yang berspesialisasi dalam bio-alchemy, ia juga menjabat sebagai asisten Albedo, kepala alkemis Ksatria Favonius.
                \r\nPreferensi Stats: Elemental Mastery > Energy Recharge > ATK%
                Prioritas Talent: (Tidak Perlu Naikan Talent)",
                'rarity' => "4star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 2,
                'weapon_alt1_genshin_id' => 136,
                'weapon_alt2_genshin_id' => 145,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 22,
                'image' => "Sucrose.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Tartaglia",
                'type' => "Bow",
                'element' => "Hydro",
                'role' => "Main DPS",
                'detail' => "Dia adalah yang kesebelas dari Sebelas Harbinger Fatui. Ke mana pun dia pergi, bahaya akan mengikutinya, dan Childe selalu ingin mencari tantangan, membuatnya sangat berbahaya meskipun dia adalah anggota termuda.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Skill > Ultimate > Basic",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 150,
                'weapon_alt1_genshin_id' => 174,
                'weapon_alt2_genshin_id' => 169,
                'artifact_opt1_id' => 20,
                'artifact_opt2_id' => 30,
                'image' => "Tartaglia.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Thoma",
                'type' => "Polearm",
                'element' => "Pyro",
                'role' => "Support",
                'detail' => "Berasal dari Mondstadt, Thoma adalah pengurus rumah tangga yang ramah dan bertanggung jawab untuk Klan Kamisato dan seorang pemecah masalah yang terkenal di Inazuma. Setelah mengumpulkan jaringan yang kuat, Thoma membela hak dan kepentingan Komisi Yashiro dengan sangat serius.
                \r\nPreferensi Stats: Energy Recharge > HP%
                Prioritas Talent: Skill = Ultimate",
                'rarity' => "4star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 99,
                'weapon_alt1_genshin_id' => 91,
                'weapon_alt2_genshin_id' => 100,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Thoma.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Tighnari",
                'type' => "Bow",
                'element' => "Dendro",
                'role' => "Sub-DPS",
                'detail' => "Tighnari adalah Kepala Penjaga Hutan yang tegas dan mentor Collei. Terlepas dari kecerdasannya, ia lebih suka hidup menyendiri di kedalaman Hutan Avidya daripada di menara gading Sumeru Akademiya.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > Elemental Mastery > ATK%
                Prioritas Talent: Basic > Ultimate",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 149,
                'weapon_alt1_genshin_id' => 174,
                'weapon_alt2_genshin_id' => 166,
                'artifact_opt1_id' => 4,
                'artifact_opt2_id' => 19,
                'image' => "Tighnari.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Venti",
                'type' => "Bow",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Dia adalah penyair Mondstadt yang berjiwa bebas dan pencinta anggur, yang menyangkal identitasnya sebagai Barbatos, Anemo Archon.
                \r\nPreferensi Stats: Elemental Mastery > Energy Recharge
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 9,
                'weapon_alt1_genshin_id' => 173,
                'weapon_alt2_genshin_id' => 159,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Venti.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Wanderer",
                'type' => "Catalyst",
                'element' => "Anemo",
                'role' => "Main DPS",
                'detail' => "Wanderer muncul menggantikan inkarnasi sebelumnya setelah yang terakhir menghapus sebutan sebelumnya dan sejarah masing-masing dari Irminsul. Menyimpan kenangan dirinya yang dulu setelah rela mendapatkannya kembali, Wanderer kini menjadi satu-satunya sebutan yang ia gunakan, karena ia tidak memiliki rumah, kerabat, atau tujuan.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > ATK
                Prioritas Talent: Basic > Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 122,
                'weapon_alt1_genshin_id' => 139,
                'weapon_alt2_genshin_id' => 132,
                'artifact_opt1_id' => 13,
                'artifact_opt2_id' => 40,
                'image' => "Wanderer.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Wriothesley",
                'type' => "Catalyst",
                'element' => "Cryo",
                'role' => "Main DPS",
                'detail' => "Setelah membunuh orang tua angkatnya yang kejam untuk menyelamatkan saudara-saudara angkatnya, Wriothesley dijatuhi hukuman dan diasingkan ke Benteng Meropide di masa remajanya. Dia akhirnya menjadi Administratornya dan telah memberlakukan serangkaian reformasi di bawah pemerintahannya, menjadi panutan bagi para tahanan.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 8,
                'weapon_alt1_genshin_id' => 128,
                'weapon_alt2_genshin_id' => 139,
                'artifact_opt1_id' => 26,
                'artifact_opt2_id' => 7,
                'image' => "Wriothesley.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Xiangling",
                'type' => "Polearm",
                'element' => "Pyro",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah Kepala Koki di Restoran Wanmin dan menjalankannya bersama ayahnya, Chef Mao. Sebagai seorang chef, Xiangling tidak takut untuk mencoba resep yang berbeda atau bahan-bahan yang “eksotis”, sehingga hidangannya terkadang cukup unik.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent:  Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 88,
                'weapon_alt1_genshin_id' => 91,
                'weapon_alt2_genshin_id' => 95,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 10,
                'image' => "Xiangling.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Xianyun",
                'type' => "Catalyst",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Xianyun, juga dikenal dengan nama adeptus-nya Cloud Retainer. Penasaran dengan apa yang menarik para muridnya ke Pelabuhan Liyue, dia tinggal di kota itu untuk melihatnya sendiri.
                \r\nPreferensi Stats: Energy Recharge > ATK% > CRIT Rate
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 114,
                'weapon_alt1_genshin_id' => 133,
                'weapon_alt2_genshin_id' => 145,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Xianyun.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Xiao",
                'type' => "Polearm",
                'element' => "Anemo",
                'role' => "Main DPS",
                'detail' => "Dia adalah seorang adeptus, dengan nama Alatus, dan satu-satunya anggota yang masih hidup dari lima Yaksha terkemuka yang dikirim oleh Morax untuk menaklukkan roh-roh jahat yang mengganggu Liyue. Saat ini dia tinggal di Penginapan Wangshu dan sebagian besar menahan diri dari keramaian dan interaksi sosial.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 86,
                'weapon_alt1_genshin_id' => 88,
                'weapon_alt2_genshin_id' => 95,
                'artifact_opt1_id' => 49,
                'artifact_opt2_id' => 13,
                'image' => "Xiao.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yae Miko",
                'type' => "Catalyst",
                'element' => "Electro",
                'role' => "Sub-DPS",
                'detail' => "Seorang kitsune yang memiliki banyak sisi, Yae Miko mengawasi Kuil Agung Narukami, memiliki Rumah Penerbitan Yae, dan merupakan pelayan serta teman Eternity.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "S",
                'weapon_sign_genshin_id' => 117,
                'weapon_alt1_genshin_id' => 138,
                'weapon_alt2_genshin_id' => 133,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 19,
                'image' => "Yae Miko.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Xingqiu",
                'type' => "Sword",
                'element' => "Hydro",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah putra kedua dari Manajer Guild dari Guild Perdagangan Feiyun, sebuah kelompok yang berpengaruh di Liyue, dan juga seorang praktisi yang memproklamirkan diri sebagai praktisi seni Klan Guhua. Juga seorang pembaca yang rajin, Xingqiu bertujuan untuk menjadi perwujudan kesatria seperti para pahlawan dari buku-buku yang dibacanya; namun, hal ini memungkiri bakatnya dalam hal kenakalan.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 15,
                'weapon_alt1_genshin_id' => 22,
                'weapon_alt2_genshin_id' => 31,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 29,
                'image' => "Xingqiu.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Xinyan",
                'type' => "Claymore",
                'element' => "Pyro",
                'role' => "Support",
                'detail' => "Rock 'n' roll adalah gaya musik yang relatif tidak populer di Liyue, karena baru-baru ini dibawa dari Fontaine. Namun, Xinyan sangat menyukai musik ini - dan dia perlahan tapi pasti mengumpulkan penggemarnya sendiri saat dia tampil di seluruh Pelabuhan Liyue.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "4star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 50,
                'weapon_alt1_genshin_id' => 71,
                'weapon_alt2_genshin_id' => 67,
                'artifact_opt1_id' => 38,
                'artifact_opt2_id' => 29,
                'image' => "Xinyan.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yanfei",
                'type' => "Catalyst",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Salah satu dari beberapa makhluk setengah binatang yang belum menandatangani kontrak dengan Rex Lapis, Yanfei tetap bekerja demi kemajuan Liyue sebagai penasihat hukum utama yang menghargai keadilan.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Energy Recharge
                Prioritas Talent: Basic > Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 120,
                'weapon_alt1_genshin_id' => 125,
                'weapon_alt2_genshin_id' => 139,
                'artifact_opt1_id' => 10,
                'artifact_opt2_id' => 19,
                'image' => "Yanfei.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yaoyao",
                'type' => "Polearm",
                'element' => "Dendro",
                'role' => "Supprt",
                'detail' => "Berasal dari daerah pedesaan yang tidak jauh dari Desa Qingce, Yaoyao tumbuh dengan alam di sisinya. Melihat potensi dalam diri Yaoyao, Streetward Rambler menerimanya sebagai murid, dan Yaoyao meninggalkan pegunungan yang tenang untuk tinggal bersama tuannya di Pelabuhan Liyue yang cerah dan ramai.
                \r\nPreferensi Stats: HP% > Energy Recharge
                Prioritas Talent: Skill = Ultimate",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 99,
                'weapon_alt1_genshin_id' => 109,
                'weapon_alt2_genshin_id' => 103,
                'artifact_opt1_id' => 11,
                'artifact_opt2_id' => 42,
                'image' => "Yaoyao.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yelan",
                'type' => "Bow",
                'element' => "Hydro",
                'role' => "Sub-DPS",
                'detail' => "Dia adalah orang misterius yang mengaku bekerja untuk Kementerian Urusan Sipil, tetapi tidak ada dalam daftar mereka. Dia juga mengaku bekerja untuk Kedai Teh Yanshang, tetapi hanya menggunakannya untuk pekerjaannya yang sebenarnya, seorang agen intelijen yang bekerja sama dengan Ningguang.
                \r\nPreferensi Stats: Energy Recharge > HP% > CRIT Rate / CRIT DMG
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 3,
                'weapon_alt1_genshin_id' => 159,
                'weapon_alt2_genshin_id' => 170,
                'artifact_opt1_id' => 15,
                'artifact_opt2_id' => 29,
                'image' => "Yelan.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yoimiya",
                'type' => "Bow",
                'element' => "Pyro",
                'role' => "Main DPS",
                'detail' => "Yoimiya adalah pemilik Naganohara Fireworks saat ini; dengan kembang api berwarna-warni dan kepribadiannya yang ramah, Yoimiya dicintai oleh semua orang di Pulau Narukami. Dia dijuluki sebagai Ratu Festival Musim Panas, karena mereka percaya bahwa musim panas tidak akan sama tanpa kehadirannya.
                \r\nPreferensi Stats: CRIT Rate / CRIT DMG > ATK% > Elemental Mastery
                Prioritas Talent: Basic > Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 153,
                'weapon_alt1_genshin_id' => 169,
                'weapon_alt2_genshin_id' => 180,
                'artifact_opt1_id' => 40,
                'artifact_opt2_id' => 10,
                'image' => "Yoimiya.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Yun Jin",
                'type' => "Polearm",
                'element' => "Geo",
                'role' => "Support",
                'detail' => "Seorang tokoh terkenal dalam dunia opera di Pelabuhan Liyue, Yun Jin adalah direktur Yun-Han Opera Troupe, dan tampil di Heyu Tea House dari waktu ke waktu. Dia juga seorang penulis naskah, telah menulis semua naskah drama yang dipentaskan oleh Yun-Han Opera Troupe dalam beberapa tahun terakhir, termasuk akhir cerita yang baru untuk The Divine Damsel of Devastation.
                \r\nPreferensi Stats: DEF% > Energy Recharge
                Prioritas Talent: Ultimate",
                'rarity' => "4star",
                'tier' => "A",
                'weapon_sign_genshin_id' => 99,
                'weapon_alt1_genshin_id' => 91,
                'weapon_alt2_genshin_id' => 105,
                'artifact_opt1_id' => 21,
                'artifact_opt2_id' => 29,
                'image' => "Yun Jin.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Zhongli",
                'type' => "Polearm",
                'element' => "Geo",
                'role' => "Support",
                'detail' => "Seorang konsultan di Rumah Duka Wangsheng, dia kemudian terungkap sebagai Geo Archon, Morax, yang telah memutuskan untuk mengalami dunia dari sudut pandang manusia.
                \r\nPreferensi Stats: HP% > Energy Recharge
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "S+",
                'weapon_sign_genshin_id' => 90,
                'weapon_alt1_genshin_id' => 99,
                'weapon_alt2_genshin_id' => 109,
                'artifact_opt1_id' => 42,
                'artifact_opt2_id' => 5,
                'image' => "Zhongli.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Traveler (Anemo)",
                'type' => "Sword",
                'element' => "Anemo",
                'role' => "Support",
                'detail' => "Traveler adalah protagonis yang dapat dimainkan di Genshin Impact. Dalam cutscene pembuka, saudara kembar dari dunia lain melakukan perjalanan melintasi alam semesta, hingga dewa yang tidak dikenal menghalangi jalan mereka. Pemain dapat memilih Aether (pria) atau Lumine (wanita) sebagai Traveler dan Saudaranya akan ditangkap. Kekuatan mereka untuk melakukan perjalanan disegel, membuat mereka terdampar di Teyvat. Mereka menyelamatkan Paimon dengan memancingnya keluar dari air dan dia menemani mereka sebagai teman perjalanan baru mereka. Bersama-sama mereka memulai perjalanan untuk menemukan The Seven dan bersatu kembali dengan saudara Traveler yang hilang.
                \r\nPreferensi Stats: Elemental Mastery > Energy Recharge > ATK%
                Prioritas Talent: (Tidak Perlu Naikan Talent)",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 10,
                'weapon_alt1_genshin_id' => 23,
                'weapon_alt2_genshin_id' => 22,
                'artifact_opt1_id' => 50,
                'artifact_opt2_id' => 29,
                'image' => "Traveler.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Traveler (Geo)",
                'type' => "Sword",
                'element' => "Geo",
                'role' => "Sub-DPS",
                'detail' => "The Traveler adalah protagonis yang dapat dimainkan di Genshin Impact. Dalam cutscene pembuka, saudara kembar dari dunia lain melakukan perjalanan melintasi alam semesta, hingga dewa yang tidak dikenal menghalangi jalan mereka. Pemain dapat memilih Aether (pria) atau Lumine (wanita) sebagai Traveler dan Saudaranya akan ditangkap. Kekuatan mereka untuk melakukan perjalanan disegel, membuat mereka terdampar di Teyvat. Mereka menyelamatkan Paimon dengan memancingnya keluar dari air dan dia menemani mereka sebagai teman perjalanan baru mereka. Bersama-sama mereka memulai perjalanan untuk menemukan The Seven dan bersatu kembali dengan saudara Traveler yang hilang.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 15,
                'weapon_alt1_genshin_id' => 23,
                'weapon_alt2_genshin_id' => 20,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Traveler.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Traveler (Electro)",
                'type' => "Sword",
                'element' => "Electro",
                'role' => "Support",
                'detail' => "The Traveler adalah protagonis yang dapat dimainkan di Genshin Impact. Dalam cutscene pembuka, saudara kembar dari dunia lain melakukan perjalanan melintasi alam semesta, hingga dewa yang tidak dikenal menghalangi jalan mereka. Pemain dapat memilih Aether (pria) atau Lumine (wanita) sebagai Traveler dan Saudaranya akan ditangkap. Kekuatan mereka untuk melakukan perjalanan disegel, membuat mereka terdampar di Teyvat. Mereka menyelamatkan Paimon dengan memancingnya keluar dari air dan dia menemani mereka sebagai teman perjalanan baru mereka. Bersama-sama mereka memulai perjalanan untuk menemukan The Seven dan bersatu kembali dengan saudara Traveler yang hilang.
                \r\nPreferensi Stats: Energy Recharge > ATK% > CRIT Rate / CRIT DMG
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 22,
                'weapon_alt1_genshin_id' => 31,
                'weapon_alt2_genshin_id' => 23,
                'artifact_opt1_id' => 29,
                'artifact_opt2_id' => 15,
                'image' => "Traveler.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Traveler (Dendro)",
                'type' => "Sword",
                'element' => "Dendro",
                'role' => "Support",
                'detail' => "The Traveler adalah protagonis yang dapat dimainkan di Genshin Impact. Dalam cutscene pembuka, saudara kembar dari dunia lain melakukan perjalanan melintasi alam semesta, hingga dewa yang tidak dikenal menghalangi jalan mereka. Pemain dapat memilih Aether (pria) atau Lumine (wanita) sebagai Traveler dan Saudaranya akan ditangkap. Kekuatan mereka untuk melakukan perjalanan disegel, membuat mereka terdampar di Teyvat. Mereka menyelamatkan Paimon dengan memancingnya keluar dari air dan dia menemani mereka sebagai teman perjalanan baru mereka. Bersama-sama mereka memulai perjalanan untuk menemukan The Seven dan bersatu kembali dengan saudara Traveler yang hilang.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG > ATK%
                Prioritas Talent: Ultimate > Skill",
                'rarity' => "5star",
                'tier' => "B",
                'weapon_sign_genshin_id' => 10,
                'weapon_alt1_genshin_id' => 22,
                'weapon_alt2_genshin_id' => 31,
                'artifact_opt1_id' => 11,
                'artifact_opt2_id' => 29,
                'image' => "Traveler.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Traveler (Hydro)",
                'type' => "Sword",
                'element' => "Hydro",
                'role' => "Sub-DPS",
                'detail' => "The Traveler adalah protagonis yang dapat dimainkan di Genshin Impact. Dalam cutscene pembuka, saudara kembar dari dunia lain melakukan perjalanan melintasi alam semesta, hingga dewa yang tidak dikenal menghalangi jalan mereka. Pemain dapat memilih Aether (pria) atau Lumine (wanita) sebagai Traveler dan Saudaranya akan ditangkap. Kekuatan mereka untuk melakukan perjalanan disegel, membuat mereka terdampar di Teyvat. Mereka menyelamatkan Paimon dengan memancingnya keluar dari air dan dia menemani mereka sebagai teman perjalanan baru mereka. Bersama-sama mereka memulai perjalanan untuk menemukan The Seven dan bersatu kembali dengan saudara Traveler yang hilang.
                \r\nPreferensi Stats: Energy Recharge > CRIT Rate / CRIT DMG
                Prioritas Talent: Skill > Ultimate",
                'rarity' => "5star",
                'tier' => "C",
                'weapon_sign_genshin_id' => 15,
                'weapon_alt1_genshin_id' => 40,
                'weapon_alt2_genshin_id' => 22,
                'artifact_opt1_id' => 2,
                'artifact_opt2_id' => 30,
                'image' => "Traveler.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
